#!/bin/sh
# Writes deploy/.env and deploy/.env.bootstrap with freshly generated secrets.
# Run once on the VPS. It refuses to overwrite, because regenerating
# SESSION_SECRET or OUTBOX_ENCRYPTION_KEY makes queued notifications
# unreadable and signs every user out.
set -eu

cd "$(dirname "$0")"

for file in .env .env.bootstrap; do
  if [ -e "$file" ]; then
    echo "deploy/$file already exists. Delete it deliberately if you mean to rotate secrets." >&2
    exit 1
  fi
done

APP_DOMAIN="${1:-}"
ACME_EMAIL="${2:-}"
if [ -z "$APP_DOMAIN" ] || [ -z "$ACME_EMAIL" ]; then
  echo "Usage: ./generate-env.sh <domain> <email-for-tls-notices>" >&2
  echo "   eg: ./generate-env.sh lessonbench.co.za you@example.com" >&2
  exit 1
fi

secret() {
  od -An -tx1 -N32 /dev/urandom | tr -d ' \n'
}

PG_ADMIN_PASSWORD="$(secret)"
PG_MIGRATOR_PASSWORD="$(secret)"
PG_RUNTIME_PASSWORD="$(secret)"
REDIS_PASSWORD="$(secret)"
STORAGE_SECRET="$(secret)"

umask 077

cat > .env <<ENV
# Generated by generate-env.sh. Secrets; never commit this file.
NODE_ENV=production
PORT=3000
APP_NAME=LessonBench

APP_DOMAIN=$APP_DOMAIN
FILES_DOMAIN=files.$APP_DOMAIN
ACME_EMAIL=$ACME_EMAIL

# Only Caddy's pinned address is trusted to set forwarded headers; a wider
# value would let any container spoof a client IP past the rate limiter.
TRUST_PROXY=172.28.0.10/32
COOKIE_SECURE=true

WEBAUTHN_ORIGIN=https://$APP_DOMAIN
WEBAUTHN_RP_ID=$APP_DOMAIN
WEBAUTHN_RP_NAME=LessonBench

POSTGRES_PASSWORD=$PG_ADMIN_PASSWORD
DATABASE_URL=postgresql://chix_runtime:$PG_RUNTIME_PASSWORD@postgres:5432/chix
REDIS_PASSWORD=$REDIS_PASSWORD
REDIS_URL=redis://:$REDIS_PASSWORD@redis:6379/0

SESSION_SECRET=$(secret)
OUTBOX_ENCRYPTION_KEY=$(secret)
RATE_LIMIT_KEY_SECRET=$(secret)

STORAGE_ENDPOINT=https://files.$APP_DOMAIN
STORAGE_REGION=us-east-1
STORAGE_BUCKET=lessonbench
STORAGE_ACCESS_KEY_ID=lessonbench
STORAGE_SECRET_ACCESS_KEY=$STORAGE_SECRET

# Registration is CAPTCHA-gated in production and the app refuses to start
# without these. Cloudflare Turnstile is free: create a widget for $APP_DOMAIN
# at dash.cloudflare.com -> Turnstile and paste both keys in.
BOT_PROTECTION_PROVIDER=turnstile
BOT_PROTECTION_SITE_KEY=
BOT_PROTECTION_SECRET_KEY=

MALWARE_SCANNER_MODE=clamav
CLAMAV_HOST=clamav
CLAMAV_PORT=3310

# Email: fill these in before onboarding anyone. Without them, sign-in codes
# are queued and encrypted but never delivered, so nobody can log in.
EMAIL_REQUIRED=true
BREVO_API_KEY=
BREVO_SENDER_EMAIL=
BREVO_SENDER_NAME=LessonBench

# Optional. Google sign-in stays hidden until both are set; the authorised
# redirect URI in Google Cloud must be https://$APP_DOMAIN exactly.
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
ENV

cat > .env.bootstrap <<ENV
# Read only by the bootstrap profile. The running app must never see these.
POSTGRES_ADMIN_URL=postgresql://chix_admin:$PG_ADMIN_PASSWORD@postgres:5432/postgres
MIGRATION_DATABASE_URL=postgresql://chix_migrator:$PG_MIGRATOR_PASSWORD@postgres:5432/chix
ENV

echo "Wrote deploy/.env and deploy/.env.bootstrap (mode 600)."
echo "Set BREVO_API_KEY and BREVO_SENDER_EMAIL in deploy/.env before going live."
