# Local Unix-socket connections require password authentication.
local   all             all                                     scram-sha-256

# TCP connections from localhost require SCRAM authentication.
host    all             all             127.0.0.1/32            scram-sha-256
host    all             all             ::1/128                 scram-sha-256

#Docker internal network requires SCRAM authentication
host    all             all             172.18.0.0/16            scram-sha-256

# Replication connections also require SCRAM authentication.
local   replication     all                                     scram-sha-256
host    replication     all             127.0.0.1/32            scram-sha-256
host    replication     all             ::1/128                 scram-sha-256
